### ISSUE TITLE
Multiprofile endpoints

### ISSUE THREAD

**Issue by Derro8** [crunchy-labs/crunchyroll-rs#26]
Multiple profiles hasn't been added yet but they've made some endpoints for it like `/accounts/v1/me/multiprofile` and `/accounts/v1/me/multiprofile/{profile_uuid}`, was thinking could add them for possible future proofing I would do it myself but I'm not confident enough in rust to do so.

These are the endpoints I could find and figure out how to use: [getMultiProfile](https://github.com/Crunchyroll-Plus/crunchyroll-docs/blob/release/Services/EtpAccount/GET/getProfile.md), [getMultiProfiles](https://github.com/Crunchyroll-Plus/crunchyroll-docs/blob/release/Services/EtpAccount/GET/getProfiles.md), [deleteMultiProfile](https://github.com/Crunchyroll-Plus/crunchyroll-docs/blob/release/Services/EtpAccount/DELETE/deleteProfile.md), [createMultiProfile](https://github.com/Crunchyroll-Plus/crunchyroll-docs/blob/release/Services/EtpAccount/POST/createProfile.md), [editMultiProfile](https://github.com/Crunchyroll-Plus/crunchyroll-docs/blob/release/Services/EtpAccount/PATCH/setProfile.md), [switchProfile](https://github.com/Crunchyroll-Plus/crunchyroll-docs/blob/release/Services/EtpAccountAuth/POST/switchProfile.md).

**Comment by ByteDream** [comment]
Are these endpoints already in use on the Crunchyroll website/app?

**Comment by Derro8** [comment]
> Are these endpoints already in use on the Crunchyroll website/app?

getProfiles: {
    path: "/accounts/v1/me/multiprofile",
    method: "GET"
},updateMultiProfile: {
                        path: "/accounts/v1/{accountId}/multiprofile/{profileId}",
                        method: "PATCH",
                        onSuccess: [n.AuthorizeInterceptor.authorize.bind(n.AuthorizeInterceptor)]
                    },

**Comment by bytedream** [comment]
Got (finally) added in [v0.11.0](https://github.com/crunchy-labs/crunchyroll-rs/releases/tag/v0.11.0)
