### ISSUE TITLE
Not detecting japanese audio locale when searching for seasons

### ISSUE THREAD

**Issue by FerrahWolfeh** [crunchy-labs/crunchyroll-rs#3]
Recently, the library stopped correctly detecting audio locales for some series, most specifically the ja_JP locale.

The code I use for querying series is exemplified as follows:
```rust
let crunchyroll = init_cr(user, password, Some(get_system_loc())).await?; //get_system_loc() is correctly setting the locale

let opts = crunchyroll_rs::search::QueryOptions::default().result_type(QueryType::Series);

let qrrs = crunchyroll.query(&self.query, opts).await?;
```

which fetches series to display in a simple selection menu.

However, some series that only have the japanese audio language are incorrectly parsed with a en_US locale, for example:
![image](https://user-images.githubusercontent.com/29310153/209376415-650517c6-e76b-49ae-bf4e-1a4c90a38524.png)

And series that have multiple dubs alongside the japanese audio don't have the ja_JP locale at all:
![image](https://user-images.githubusercontent.com/29310153/209376567-d472ec3e-c6c2-461d-b7bf-8ea4a2b469ef.png)

**Comment by adracea** [comment]
Hey there, this seems to be a recent change in crunchyroll? I've looked at quite a few different series and seemingly the ja-JP locale has disappeared or is wrongly reported as en-US which creates quite some confusion. One way to get the proper version would be to look for `Series.is_subbed` or `Series.is_dubbed`.

**Comment by FerrahWolfeh** [comment]
I tried rewriting the audio selection logic for my app, but I ended giving up on it for now. Yes, it is possible to guide myself using those two flags mentioned above, but it started to complicate things quite a bit...

Hoping for a better fix for the issue and good holidays :+1:

**Comment by FerrahWolfeh** [comment]
Just a heads-up: seems like aniDL's [multi-downloader-nx](https://github.com/anidl/multi-downloader-nx) is still correctly parsing the languages even in very older versions. They might do something different from what happens here...

**Comment by adracea** [comment]
> Just a heads-up: seems like aniDL's [multi-downloader-nx](https://github.com/anidl/multi-downloader-nx) is still correctly parsing the languages even in ancient versions of their utility. They might do something different from what happens here...

I believe that that is impossible ? Crunchyroll itself is, right now, reporting that all series and episodes no matter their *actual* locale are in en-US.
Example: chainsaw-man first ep in ja-JP audio : 
![image](https://user-images.githubusercontent.com/6214663/209464220-3062833d-22ff-4ef3-97f6-73fc58572fe2.png)

**Comment by FerrahWolfeh** [comment]
I took a good look at their parsing code and it looks like they never actually read the `audio_locale` field. Instead, they assume the season language from the season title, which is one kinda an interesting idea

something like this:
```typescript
for (const item of seasonsList.items) {
      for (const lang of langsData.languages) {
        if (!Object.prototype.hasOwnProperty.call(ret, item.season_number))
          ret[item.season_number] = {};
        if (item.title.includes(`(${lang.name} Dub)`) || item.title.includes(`(${lang.name})`)) {
          ret[item.season_number][lang.code] = item;
        } else if (item.is_subbed && !item.is_dubbed && lang.code == 'jpn') {
          ret[item.season_number][lang.code] = item;
        } else if (item.is_dubbed && lang.code === 'eng' && !langsData.languages.some(a => item.title.includes(`(${a.name})`) || item.title.includes(`(${a.name} Dub)`))) { // Dubbed with no more infos will be treated as eng dubs
          ret[item.season_number][lang.code] = item;
        }
      }
    }
    return ret;
```

**Comment by FerrahWolfeh** [comment]
Now one thing that may be missing from the lib's code are the flags for `is_subbed` and `is_dubbed` present in the season object, which aren't present by now

**Comment by ByteDream** [comment]
> I took a good look at their parsing code and it looks like they never actually read the `audio_locale` field. Instead, they assume the season language from the season title, which is one kinda an interesting idea
> 
> something like this:
> 
> ```ts
> for (const item of seasonsList.items) {
>       for (const lang of langsData.languages) {
>         if (!Object.prototype.hasOwnProperty.call(ret, item.season_number))
>           ret[item.season_number] = {};
>         if (item.title.includes(`(${lang.name} Dub)`) || item.title.includes(`(${lang.name})`)) {
>           ret[item.season_number][lang.code] = item;
>         } else if (item.is_subbed && !item.is_dubbed && lang.code == 'jpn') {
>           ret[item.season_number][lang.code] = item;
>         } else if (item.is_dubbed && lang.code === 'eng' && !langsData.languages.some(a => item.title.includes(`(${a.name})`) || item.title.includes(`(${a.name} Dub)`))) { // Dubbed with no more infos will be treated as eng dubs
>           ret[item.season_number][lang.code] = item;
>         }
>       }
>     }
>     return ret;
> ```

I have also already thought about how and if this can be done by name parsing. But I don't like the idea because Crunchyroll is Crunchyroll and sometimes does magic🪄 things which screws up everything. But if it works reliable (does it?) with the mentioned repo it might get implemented in the lib.

**Comment by FerrahWolfeh** [comment]
> But if it works reliable (does it?) with the mentioned repo it might get implemented in the lib.

Well, pretty much, it seems.
I've looked through the commits of that repo and that parsing function is pretty much the same logic since a good while.

Also I used to use multi-downloader-nx for some time and never updated once. It always seemed to work reliably

**Comment by FerrahWolfeh** [comment]
Great! As can be seen below, the episodes are correctly parsed according to the selected language (`ja_JP`, ignore the portuguese name of the EPs), but the series objects still only have the incorrect `en_US` locale... Nothing very significant though.

![image](https://user-images.githubusercontent.com/29310153/210256739-3b8d77e2-0603-4f75-9e61-158f66f9c5ff.png)

**Comment by adracea** [comment]
The series objects having the wrong locale is strictly something coming from crunchyroll itself sadly(as I mentioned above and the main reason for the changes). Sadly it's nothing we can handle.

**Comment by ByteDream** [comment]
This should be fixed now tho. With `CrunchyrollBuilder::stabilization_locales(true)` set, the series fetches the audio locale from its seasons, sums them up, and set it as `Series::audio_locales`.
https://github.com/crunchy-labs/crunchyroll-rs/blob/04feae0ffb86dcfaae55f4793510bb2137b9eb1f/src/media/media.rs#L97-L109

**Comment by ByteDream** [comment]
I tracked down why it doesn't work. I set the client to request all seasons _after_ trying to use it, which obviously doesn't work. Thought it should be, my bad.

> Great! As can be seen below, the episodes are correctly parsed according to the selected language (`ja_JP`, ignore the portuguese name of the EPs), but the series objects still only have the incorrect `en_US` locale... Nothing very significant though.
> 
> ![image](https://user-images.githubusercontent.com/29310153/210256739-3b8d77e2-0603-4f75-9e61-158f66f9c5ff.png)

_Now_ with [v.0.2.2](https://github.com/crunchy-labs/crunchyroll-rs/releases/tag/v0.2.2) it should work. I thought that it worked but after some testing I also saw it didn't.
