### ISSUE TITLE
BrowseSortType not working as expected with browse()

### ISSUE THREAD

**Issue by ShivamB25** [crunchy-labs/crunchyroll-rs#31]
## Description
I'm currently facing an issue while attempting to utilize the `sort()` method within the `BrowseOptions` during a call to `browse()`. Strangely, regardless of the selected `BrowseSortType`, the results returned do not adhere to the specified sorting order.

## Steps to Reproduce
1. Construct `BrowseOptions` with a specified sort type (e.g., `Popularity`, `NewlyAdded`, etc.).
2. Invoke the `browse()` method using the constructed `BrowseOptions`.
3. Examine the results for the sorting order.

## Expected Behavior
The outcome of the `browse()` function should align with the specified `BrowseSortType` within the `BrowseOptions`.

## Actual Behavior
Contrary to expectations, the results are not sorted in accordance with the chosen `BrowseSortType`. For instance, when utilizing `Popularity`, the anticipated order is from most to least popular. However, the returned list does not conform to this expected sorting.

## Code Snippet

```rust
// Example code illustrating the issue
let crunchyroll = Crunchyroll::builder()
    .login_with_credentials(email, password)
    .await?;

let options = BrowseOptions::default().sort(crunchyroll_rs::search::BrowseSortType::NewlyAdded);

let mut browse_result = crunchyroll.browse(options.clone());
// The results are not sorted by newlyadded
```

## Environment Information
- **Rust Version**: 1.74.0
- **`crunchyroll-rs` Version**: 0.8.0
- **Operating System**: Windows 11
---

**Comment by ShivamB25** [comment]
bumpa

**Comment by bytedream** [comment]
Thanks for reporting. Crunchyroll renamed some query parameters, it should work again in [v0.8.1](https://github.com/crunchy-labs/crunchyroll-rs/releases/tag/v0.8.1)
